forum/urls.py
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.FriendsPostList.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^register/$', views.register, name='register'),

    path('user_profile/<int:pk>/', views.ShowProfilePageView.as_view(), name='user_profile'),
    path('create_profile_page/', views.CreateProfilePageView.as_view(), name='create_user_profile'),
    path('update_user_profile/<int:pk>/', views.UpdateProfilePageView.as_view(), name='update_user_profile'),
    re_path(r'^send_request/(?P<spk>\d+)/(?P<rpk>\d+)/$', views.send_request, name='send_request'),
    re_path(r'^friend_requests/$', views.UserFriendRequests.as_view(), name='user_friend_requests'),
    re_path(r'^connect/(?P<operation>.+)/(?P<pk>\d+)$', views.change_friend, name='change_friend'),
    re_path(r'^remove/(?P<pk>\d+)$', views.remove_friend, name='remove_friend'),
    re_path(r'^friends/$', views.FriendList.as_view(), name='friends'),
    re_path(r'^all_users/$', views.AllUserList.as_view(), name='all_users'),
    path('create_post/', views.CreatePost.as_view(), name='create_post'),
    path('update_post/<int:pk>/', views.UpdatePost.as_view(), name='update_post'),
    path('delete_post/<int:pk>/', views.DeletePost.as_view(), name='delete_post'),
    re_path(r'^my_posts/$', views.MyPostsList.as_view(), name='my_posts'),
    re_path(r'^user_posts/(?P<pk>\d+)$', views.UserPostsList.as_view(), name='user_posts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    first_name = models.CharField("first name", max_length=100)
    last_name = models.CharField("last name", max_length=100)
    profile_pic = models.ImageField(null=True, blank=True, upload_to="images/profile/")
    avatar_thumbnail = ImageSpecField(source='profile_pic',
                                      processors=[ResizeToFill(512, 512)],
                                      format='JPEG',
                                      options={'quality': 100})
    date_of_birth = models.DateField(null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    facebook = models.CharField(max_length=50, null=True, blank=True)
    twitter = models.CharField(max_length=50, null=True, blank=True)
    instagram = models.CharField(max_length=50, null=True, blank=True)

    SEX_STATUS = (
        ('m', 'male'),
        ('f', 'female'),
    )

    sex = models.CharField(max_length=1, choices=SEX_STATUS, blank=True, default='m')

    def __str__(self):
        return str(self.user)


class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True, on_delete=models.CASCADE)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)
        new_friend, new_created = cls.objects.get_or_create(
            current_user=new_friend
        )
        new_friend.users.add(current_user)

    @classmethod
    def lose_friend(cls, current_user, ex_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(ex_friend)
        new_friend, new_created = cls.objects.get_or_create(
            current_user=ex_friend
        )
        new_friend.users.remove(current_user)


class FriendRequest(models.Model):
    sender = models.ForeignKey(User, related_name='sender', on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name='recipient', on_delete=models.CASCADE)


class Post(models.Model):
    current_user = models.ForeignKey(User, related_name='post_owner', null=True, on_delete=models.CASCADE)
    head = models.CharField("Заголовок", max_length=100)
    text = models.TextField("Текст", null=True, blank=True)
    date = models.DateField(null=True, blank=True)

forum/forms.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import ModelForm, CharField, PasswordInput, TextInput, ClearableFileInput, Textarea
from .models import Profile, Post


class UserRegistrationForm(ModelForm):
    password = CharField(label='Password', widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = CharField(label='Repeat password', widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

        widgets = {
            'username': TextInput(attrs={'class': 'form-control'}),
            'email': TextInput(attrs={'class': 'form-control'}),
        }


    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise ValidationError('Пароль не совпадает')
        return cd['password2']


class ProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_pic', 'first_name', 'last_name', 'bio')

        widgets = {
            'profile_pic': ClearableFileInput(),
            'first_name': TextInput(attrs={'class': 'form-control'}),
            'last_name': TextInput(attrs={'class': 'form-control'}),
            'bio': Textarea(attrs={'class': 'form-control'}),
        }


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('head', 'text')

        widgets = {
            'head': TextInput(attrs={'class': 'form-control'}),
            'text': Textarea(attrs={'class': 'form-control'}),
        }

forum/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User, AnonymousUser
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy

from .forms import UserRegistrationForm, ProfileUpdateForm, PostForm
from .models import Profile, FriendRequest, Friend, Post
from django.views.generic import DetailView, UpdateView, DeleteView, ListView, CreateView

from datetime import date

# Create your views here.
def index(request):
    return render(
        request,
        'forum/index.html',
    )


class ShowProfilePageView(DetailView):
    model = Profile
    template_name = 'forum/user_profile.html'

    def get_context_data(self, *args, **kwargs):
        users = Profile.objects.all()
        context = super(ShowProfilePageView, self).get_context_data(*args, **kwargs)
        page_user = get_object_or_404(Profile, id=self.kwargs['pk'])
        context['page_user'] = page_user
        return context


class CreateProfilePageView(CreateView):
    model = Profile

    template_name = 'forum/create_profile.html'
    form_class = ProfileUpdateForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url = reverse_lazy('home')


class UpdateProfilePageView(UpdateView):
    model = Profile
    form_class = ProfileUpdateForm

    template_name = 'forum/update_profile.html'
    #fields = ['profile_pic', 'first_name', 'last_name', 'bio', 'facebook', 'twitter', 'instagram']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url = reverse_lazy('home')


def send_request(request, spk, rpk):
    if request.user.id == int(spk) and spk != rpk:
        recipient = User.objects.get(pk=int(rpk))
        if (FriendRequest.objects.filter(recipient=recipient, sender=request.user)):
            print("такое уже есть")
        else:
            FriendRequest.objects.create(recipient=recipient, sender=request.user)
    return redirect('all_users')


class UserFriendRequests(LoginRequiredMixin, ListView):
    model = FriendRequest
    template_name = 'forum/user_friend_requests.html'
    paginate_by = 10

    def get_queryset(self):
        return FriendRequest.objects.filter(recipient=self.request.user)


def change_friend(request, operation, pk):
    req = FriendRequest.objects.get(pk=pk)
    friend = req.sender
    if operation == 'add':
        Friend.make_friend(friend, request.user)
    req.delete()
    return redirect('user_friend_requests')


def remove_friend(request, pk):
    friend = User.objects.get(pk=pk)
    Friend.lose_friend(friend, request.user)
    return redirect('friends')


class AllUserList(ListView):
    model = Profile
    template_name = 'forum/user_list.html'
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Profile.objects.filter(Q(first_name=query) | Q(last_name=query))
        else:
            return Profile.objects.all()


class FriendList(ListView):
    model = Profile

    template_name = 'forum/friend_list.html'
    paginate_by = 5

    def get_queryset(self):
        if Friend.objects.filter(current_user=self.request.user):
            return Friend.objects.get(current_user=self.request.user).users.all()
        else:
            Friend.objects.get_or_create(current_user=self.request.user)
            return ''


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'user_form': user_form})


class CreatePost(CreateView):
    model = Post

    template_name = 'forum/create_post.html'
    form_class = PostForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.current_user = self.request.user
        obj.date = date.today()
        obj.save()
        return super().form_valid(form)

    success_url = reverse_lazy('my_posts')


class UpdatePost(UpdateView):
    model = Post

    template_name = 'forum/update_post.html'
    form_class = PostForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.date = date.today()
        obj.save()
        return super().form_valid(form)

    success_url = reverse_lazy('my_posts')


class DeletePost(DeleteView):
    model = Post

    success_url = reverse_lazy('my_posts')


class MyPostsList(ListView):
    model = Post
    template_name = 'forum/my_posts.html'
    paginate_by = 3

    def get_queryset(self):
        return Post.objects.filter(current_user=self.request.user).order_by('-date')


class UserPostsList(ListView):
    model = Post
    template_name = 'forum/user_posts.html'
    paginate_by = 3

    def get_queryset(self):
        user = User.objects.get(pk=int(self.kwargs['pk']))
        return Post.objects.filter(current_user=user).order_by('-date')


class FriendsPostList(ListView):
    model = Post
    template_name = 'forum/fiends_posts.html'
    paginate_by = 3

    def get_queryset(self):
        user = self.request.user
        try:
            return Post.objects.filter(current_user__in=Friend.objects.get(current_user=user).users.all()).order_by('-date')
        except:
            return ''

forum/templates/forum/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  {% block title %}<title>Forum</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<title>Whitesquare</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css">
</head>

<body>
    <div id="wrapper">
        <nav>
            <ul class="top-menu">
                <li><a href="{% url 'home' %}">HOME</a></li>
            </ul>
        </nav>
		<aside>
            <nav>
                {% block sidebar %}
                <ul class="aside-menu">
                </ul>
                {% if user.is_authenticated %}
                <hr>
                <li><font color="green">Пользователь:</font> {{ user.get_username }}</li>

                {% if user.profile %}
                <li><a href="{% url 'user_profile' user.profile.id %}">Профиль</a></li>
                {% else %}
                <li><a href="{% url 'create_user_profile' %}">Создать профиль</a></li>
                {% endif %}

                <li><a href="{% url 'my_posts' %}">Мои посты</a></li>

                <li><a href="{% url 'logout'%}?next={% url 'home' %}"><font color="red">Выйти</font></a></li>

                {% if user.profile %}
                <hr>
                <li><a href="{% url 'user_friend_requests'%}">Заявки</a></li>
                <hr>
                <li><a href="{% url 'friends'%}">Друзья</a></li>
                <li><a href="{% url 'all_users'%}">Все пользователи</a></li>
                {% endif %}

                {% if user.is_staff %}
                <hr>
                staff
                {% endif %}
                {% else %}
                <li><a href="{% url 'login'%}?next={{request.path}}">Войти</a></li>
                {% endif %}
                {% endblock %}
            </nav>
        </aside>

		<section>
        <div class="container-fluid" style="min-height: 350px">
            <div class="row">
            <div class="col-sm-2">

            </div>
                <div class="col-sm-10 ">
                    {% block content %}{% endblock %}

                    {% block pagination %}
                    {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">назад</a>
                            {% endif %}
                            <span class="page-current">
                                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">вперед</a>
                            {% endif %}
                        </span>
                    </div>
                    {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
        </section>
    </div>
    <footer class="text-center text-lg-start bg-light text-muted navbar-fixed-bottom">
      <!-- Section: Links  -->
        <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.05);">
            <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>ABOUT
                        </h6>
                        <p>
                            Меня зовут Артем Завгороднев, я студент 1 курса ДВФУ, Прикладная математика и информатика. И этот сайт - моё домашнее задание.
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">
                            Contact
                        </h6>
                        <p><i class="fas fa-home me-3"></i> Russia, VL</p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            zavgorodnev.artem@gmail.com
                        </p>
                        <p><i class="fas fa-phone me-3"></i> +7 (999) 05-70-617</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
<!-- Footer -->
</body>
</html>

forum/templates/forum/create_post.html
{% extends "forum/base.html" %}

{% block title %}
<title>Create Post</title>
{% endblock %}

{% block content %}
    <div class="header-bar">
        <h1>Создание поста</h1><br><br>
    </div>
    {% if request.user.is_authenticated %}
        <div class="card-body">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Опубликовать</button>
        </form>
        </div>
    {% else %}
    <a href="{% url 'login' %}" class="green">Login</a>
{% endif %}
{% endblock content %}

forum/templates/forum/create_profile.html
{% extends "forum/base.html" %}

{% block title %}
<title>Create Profile</title>
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        {% if not request.user.profile %}
        <div class="card-body">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Добавить</button>
        </form>
        </div>
        {% else %}
        <p>у вас уже есть профиль</p>
        {% endif %}
    {% else %}
    <a href="{% url 'login' %}">Login</a>
{% endif %}
{% endblock content %}

forum/templates/forum/fiends_posts.html
{% extends "forum/base.html" %}

{% block title %}
<title>Посты пользователя</title>
{% endblock %}

{% load static %}
{% block content %}
<ul>
        <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">Посты друзей</h6>
        {% if post_list %}
        {% for post in post_list %}
            <div class="media text-muted pt-3">
                <div class="d-flex justify-content-between align-items-center w-100">
                        <nav><strong class="text-gray-dark"><a href="{% url 'user_profile' post.current_user.profile.id %}" class="link-secondary">{{ post.current_user.profile.first_name }} {{ post.current_user.profile.last_name }}</a></strong></nav><hr>
                </div>
                <div class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                    <strong><span class="d-block">{{post.head}}</span></strong>
                    {{post.text}}<br><br>
                    {{post.date}}
                </div>
            </div>
            {% endfor %}
        {% else %}
        <p>Еще нет постов.</p>
        {% endif %}
        </div>
    </ul>
{% endblock content %}

forum/templates/forum/friend_list.html
{% extends "forum/base.html" %}

{% block title %}
<title>Друзья</title>
{% endblock %}

{% load static %}
{% block content %}
    <h1>Список друзей</h1>
    <br><br>
    {% if user_list %}
        <ul class="list-group">
      {% for user in user_list %}
        {% if user.profile %}
            <ul class="list-group-item">
        <h4><a href="{% url 'user_profile' user.profile.id %}" class="no-decoration">{{user.profile.first_name}} {{user.profile.last_name}}</a></h4>
        {% if user.profile.profile_pic %}
          <img src="{{ user.profile.avatar_thumbnail.url }}" height=30 width=30 class="round" alt="">
        {% else %}
          <img src="{% static 'media/images/profile/user.png' %}" height=30 width=30 class="round" alt="">
        {% endif %}
        <a href="{% url 'remove_friend' user.id %}" class="red">Удалить из друзей</a><br><br>
        {% endif %}
                </ul>
        {% endfor %}
    </ul>
    {% else %}
      <p>Таких друзей нет</p>
    {% endif %}
{% endblock content %}

forum/templates/forum/index.html
{% extends "forum/base.html" %}

{% block title %}
<title>Home</title>
{% endblock %}

{% block content %}
<h1>Forum</h1>
  <p>Welcome to <em>Forum</em>, create by Artem.</p>
{% endblock %}

forum/templates/forum/my_posts.html
{% extends "forum/base.html" %}

{% block title %}
<title>Мои посты</title>
{% endblock %}

{% load static %}
{% block content %}
<ul>
        <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">Мои посты</h6>
        {% if post_list %}
        {% for post in post_list %}
            <div class="media text-muted pt-3">
                <div class="d-flex justify-content-between align-items-center w-100">
                        <nav><strong class="text-gray-dark"><a href="{% url 'user_profile' post.current_user.profile.id %}" class="link-secondary">{{ post.current_user.profile.first_name }} {{ post.current_user.profile.last_name }}</a></strong></nav><hr>
                </div>
                <div class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                    <strong><span class="d-block">{{post.head}}</span></strong>
                    {{post.text}}<br><br>
                    {{post.date}}<br><br>
                    <a href="{% url 'update_post' post.id %}" class="gray">Редактировать</a>
                    <a href="{% url 'delete_post' post.id %}" class="red">Удалить</a>
                </div>
            </div>
            {% endfor %}
            <div class="media text-muted pt-3">
                <div class="media-body pb-3 mb-0  lh-125 border-bottom border-gray">
                    <span class="d-block"><a href="{% url 'create_post' %}" class="green">Новый пост</a></span>
                </div>
            </div>
        {% else %}
        <p>У вас еще нет постов. Опубликуйте что-нибудь скорее.</p>
            <div class="media text-muted pt-3">
                <div class="media-body pb-3 mb-0  lh-125 border-bottom border-gray">
                    <span class="d-block"><a href="{% url 'create_post' %}" class="green">Новый пост</a></span>
                </div>
            </div>
        {% endif %}
        </div>
    </ul>
{% endblock content %}

forum/templates/forum/post_confirm_delete.html
{% extends "forum/base.html" %}

{% block title %}
<title>Delete post</title>
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
    <p>Вы действительно хотите удалить пост "<strong>{{ object.head }}</strong>"?</p>
    {{ form }}
    <input type="submit" value="Да, удалить">
    </form>
{% endblock content %}

forum/templates/forum/update_post.html
{% extends "forum/base.html" %}

{% block title %}
<title>Create Post</title>
{% endblock %}

{% block content %}
    <div class="header-bar">
        <h1>Редактирование поста</h1><br><br>
    </div>
    {% if request.user.is_authenticated %}
        <div class="card-body">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Изменить</button>
        </form>
        </div>
    {% else %}
    <a href="{% url 'login' %}" class="green">Login</a>
{% endif %}
{% endblock content %}

forum/templates/forum/update_profile.html
{% extends "forum/base.html" %}

{% block title %}
<title>Update Profile</title>
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="card-body">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Добавить</button>
        </form>
        </div>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
{% endif %}
{% endblock content %}

forum/templates/forum/user_friend_requests.html
{% extends "forum/base.html" %}

{% block title %}
<title>Friend Requests</title>
{% endblock %}

{% load static %}
{% block content %}
    <h1>Заявки в друзья</h1><br><br>
    {% if friendrequest_list %}
    <ul class="list-group">
      {% for friendreq in friendrequest_list %}
        <ul class="list-group-item">
            <h3>
        {% if friendreq.sender.profile.profile_pic %}
          <img src="{{ friendreq.sender.profile.avatar_thumbnail.url }}" height=40 width=40 class="round" alt="">
        {% else %}
          <img src="{% static 'media/images/profile/user.png' %}" height=30 width=30 class="round" alt="">
        {% endif %}
            </h3>
            <h2>
        <a href="{% url 'user_profile' friendreq.sender.id %}?next={{request.path}}" class="no-decoration">
        {{friendreq.sender.profile.first_name}} {{friendreq.sender.profile.last_name}}</a>
            </h2>
            <a href="{% url 'change_friend' 'add' friendreq.id %}" class="green">принять</a>
        <a href="{% url 'change_friend' 'nothing' friendreq.id %}" class="red">отклонить</a>
        </ul>
        {% endfor %}
    </ul>
    {% else %}
      <p>Нет заявок в друзья</p>
    {% endif %}
{% endblock content %}

forum/templates/forum/user_list.html
{% extends "forum/base.html" %}

{% block title %}
<title>Пользователи</title>
{% endblock %}

{% load static %}
{% block content %}
    <h1>Список пользователей</h1><br><br>
    <form action="{% url 'all_users' %}" method="get">
        <input name="q" type="text" placeholder="Search...">
    </form>
    <br>
    {% if profile_list %}
    <ul class="list-group">
      {% for profile in profile_list %}
        <ul class="list-group-item">
            <h3>
        {% if profile.profile_pic %}
          <img src="{{ profile.avatar_thumbnail.url }}" height=40 width=40 class="round" alt="">
        {% else %}
          <img src="{% static 'media/images/profile/user.png' %}" height=30 width=30 class="round" alt="">
        {% endif %}
                </h3>
        <h2><a href="{% url 'user_profile' profile.id %}" class="no-decoration">{{profile.first_name}} {{profile.last_name}}</a></h2>
        </ul>
        {% endfor %}
    </ul>
    {% else %}
      <p>Пользователей нет</p>
    {% endif %}
{% endblock content %}

forum/templates/forum/user_posts.html
{% extends "forum/base.html" %}

{% block title %}
<title>Посты пользователя</title>
{% endblock %}

{% load static %}
{% block content %}
<ul>
        <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">Посты пользователя</h6>
        {% if post_list %}
        {% for post in post_list %}
            <div class="media text-muted pt-3">
                <div class="d-flex justify-content-between align-items-center w-100">
                        <nav><strong class="text-gray-dark"><a href="{% url 'user_profile' post.current_user.profile.id %}" class="link-secondary">{{ post.current_user.profile.first_name }} {{ post.current_user.profile.last_name }}</a></strong></nav><hr>
                </div>
                <div class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                    <strong><span class="d-block">{{post.head}}</span></strong>
                    {{post.text}}<br><br>
                    {{post.date}}
                </div>
            </div>
            {% endfor %}
        {% else %}
        <p>У этого пользователя еще нет постов.</p>
        {% endif %}
        </div>
    </ul>
{% endblock content %}

forum/templates/forum/user_profile.html
{% extends "forum/base.html" %}

{% block title %}
<title>{{ page_user }}</title>
{% endblock %}

{% load static %}
{% block content %}

    <div class="header-bar">
        <h1>Профиль</h1><br><br>
    </div>

    <div class="card-body">
    {% if profile.profile_pic %}
      <img src="{{ profile.avatar_thumbnail.url }}" height=200 width=200 class="round" alt=""><br><br>
    {% else %}
      <img src="{% static 'media/images/profile/user.png' %}" height=100 width=100 class="round" alt=""><br><br>
    {% endif %}
      <p><strong>Имя:</strong> {{ profile.first_name }}</p>
      <p><strong>Фамилия:</strong> {{ profile.last_name }}</p>
      <p><strong>О себе:</strong> {{ profile.bio }}</p><br>
      {% if profile.twitter %}
      <p><strong>Twitter:</strong> {{ profile.twitter }}</p><br><br>
      {% endif %}
      {% if profile.instagram %}
      <p><strong>Instagram:</strong> {{ profile.instagram }}</p><br><br>
      {% endif %}
      {% if profile.facebook %}
      <p><strong>Facebook:</strong> {{ profile.facebook }}</p><br><br>
      {% endif %}

        {% if user.is_authenticated %}
            {% if user.id == profile.user.id %}
                <a href="{% url 'update_user_profile' user.profile.id %}" class="green">Изменить</a>
                <hr>
                <a href="{% url 'my_posts' %}" class="gray">Мои посты</a>
                {% else %}
                <a href="{% url 'send_request' user.id profile.user.id %}?next={{request.path}}" class="green">Добавить в друзья</a>
                <hr>
                <a href="{% url 'user_posts' profile.user.id %}" class="gray">Посты</a>
            {% endif %}
        {% endif %}



    </div>

{% endblock content %}